#!/usr/bin/env bash
# This script reads /etc/passwd and displays username, user id, and home directory
while IFS=: read -r username password userid groupid gecos home shell
do
	echo "$username:$userid:$home"
done < /etc/passwd
